# Wokwi Configuration File
# Reference: https://docs.wokwi.com/vscode/project-config
[wokwi]
version = 1
firmware = 'target/riscv32imac-unknown-none-elf/release/esp32-c6-wdt-test'
elf = 'target/riscv32imac-unknown-none-elf/release/esp32-c6-wdt-test'
